export const contentsByDay = [
	{ imgSrc: "assets/days/01.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bmowhz/cheddar_uras%C3%A1g_gyarapodik/", text: "Cheddar uraság gyarapodik" },
	{ imgSrc: "assets/days/02.webp", url: "https://www.reddit.com/r/IllegallySmolCats/comments/1bmhrw5/adopted_kitty_from_someone_on_reddit_looking_for/", text: "Adopted kitty from someone on Reddit. Looking for suggestions - what should we name her? :3" },
	{ imgSrc: "assets/days/03.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bmstvs/hogy_%C3%A9rted_hogy_ne_b%C3%BAjjak_a_seggedbe/", text: "Hogy érted, hogy ne bújjak a seggedbe?" },
	{ imgSrc: "assets/days/04.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bmgxi3/ugye_m%C3%A9g_j%C3%A1tszol_velem/", text: "Ugye még játszol velem?" },
	{ imgSrc: "assets/days/05.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bl133g/nehogy_m%C3%A1r_ne_vele_foglalkozzak_munkaid%C5%91ben/", text: "Nehogy már ne vele foglalkozzak munkaidőben!😄" },
	{ imgSrc: "assets/days/06.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bkz29g/de_sz%C3%A9p_macska_vagy_karmi/", text: "De szép macska vagy Karmi…🤫❤️" },
	{ imgSrc: "assets/days/07.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bhy20s/pityi_j%C3%B3l_meg%C3%A9rdemelt_pihen%C5%91je_egy_hossz%C3%BA_nap_ut%C3%A1n/", text: "Pityi jól megérdemelt pihenője egy hosszú nap után" },
	{ imgSrc: "assets/days/08.png", url: "https://www.reddit.com/r/IllegallySmolCats/comments/1bi1a6m/jables_trying_to_nurse_on_one_of_my_older_cats/", text: "Jables trying to nurse on one of my older cats that is definitely not his mom" },
	{ imgSrc: "assets/days/09.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bgc7uk/tavaszi_illatok/", text: "Tavaszi illatok" },
	{ imgSrc: "assets/days/10.jpg", url: "https://www.reddit.com/r/IllegallySmolCats/comments/1bh2pxm/smol_mobster_does_a_mayhem_and_then_swims_with_da/", text: "Smol mobster does a mayhem and then swims with da fishes." },
	{ imgSrc: "assets/days/11.jpg", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bgzcox/t%C3%A1mad%C3%A1s/", text: "Támadás 🤣" },
	{ imgSrc: "assets/days/12.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bh21o2/900_grammnyi_d%C3%ADszp%C3%A9ld%C3%A1ny/", text: "900 grammnyi díszpéldány" },
	{ imgSrc: "assets/days/13.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bdcbo4/ezio_nem_%C3%A9rti_a_gazd%C3%A1ja_mi%C3%A9rt_f%C3%BCrdik_%C3%B6nsz%C3%A1nt%C3%A1b%C3%B3l/", text: "Ezio nem érti a gazdája miért fürdik önszántából" },
	{ imgSrc: "assets/days/14.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bgs1z0/nagyszem%C5%B1/", text: "Nagyszemű" },
	{ imgSrc: "assets/days/15.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bg5ni7/valami_sose_v%C3%A1ltozik/", text: "Valami sose változik" },
	{ imgSrc: "assets/days/16.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bdnwz8/amikor_k%C3%A9rdik_hogy_mi%C3%A9rt_kell_xl_eg%C3%A9rpad/", text: "Amikor kérdik, hogy miért kell XL egérpad..." },
	{ imgSrc: "assets/days/17.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bfdwc8/hello/", text: "Hello." },
	{ imgSrc: "assets/days/18.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bfbxng/alvin_a_be%C3%A9p%C3%ADthet%C5%91_macska/", text: "Alvin, a beépíthető macska" },
	{ imgSrc: "assets/days/19.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bg2224/testes/", text: "Testes" },
	{ imgSrc: "assets/days/20.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bg13tx/szombati_szer%C3%A9nke_photodump/", text: "Szombati Szerénke photodump" },
	{ imgSrc: "assets/days/21.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bfm8hy/a_falusi_garfield/", text: "A falusi Garfield" },
	{ imgSrc: "assets/days/22.png", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bf9s0q/onlycat/", text: "Onlycat😆😆" },
	{ imgSrc: "assets/days/23.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bcus29/csofika_rosszalkodik/", text: "Csofika rosszalkodik" },
	{ imgSrc: "assets/days/24.webp", url: "https://www.reddit.com/r/dagadtmacskak/comments/1bemlvf/terroriz%C3%A1lom_any%C3%A1mat_am%C3%ADg_napozik/", text: "Terrorizálom anyámat amíg napozik" },
]